config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  	sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
 #上はデバイスのコントローラのカスタマイズ

  get '/' => "customers/homes#top", as: 'home'
  get 'homes/about' => "customers/homes#about",as: 'about'
  get 'homes/how_to_use' => "customers/homes#how_to_use",as: 'how_to_use'
  get 'homes/privacy' => "customers/homes#privacy",as: 'privacy'
  get '/people/search' => 'customers/people#search'
  get '/books/search' => 'customers/books#search'
  post '/people/:person_id/books/:book_id/favorites' => "customers/favorites#create", as: "like"
  delete '/people/:person_id/books/:book_id/favorites' => "customers/favorites#destroy", as: "dislike"

  scope module: 'customers' do
    resources :customers, only:[:edit, :update, :destroy, :show]
    get 'customer/destruction'=> "customers#destruction"
    resources :notifications, only: [:index, :destroy]
    resources :books, only: [:index,:destroy]
    resources :people, only:[:index, :create, :show, :edit, :update, :new] do
      resources :portraits, only:[:index, :create, :destroy]
      resources :creations, only:[:new,:index, :create, :edit, :update, :destroy]
      resources :books, only:[:new,  :create, :edit, :update, :destroy]
    end
  end
    devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :people, only: [:index, :destroy]
    resources :tags, only: [:index, :destroy, :edit, :update]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :customer
	belongs_to :person, optional: true
	has_many :favorites, dependent: :destroy
	has_many :notifications, dependent: :destroy
  has_many :book_tags, dependent: :destroy, foreign_key: 'book_id'
  has_many :tags, through: :book_tags
  attachment :scribble
	validates :title, presence:true
	validates :caption, presence:true
  validates :grade, presence:true

	def favorited_by?(customer)
		favorites.where(customer_id: customer.id).exists?
	end

  def create_notification_by(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and book_id = ? and action = ? ",
                                  current_customer.id, customer_id, id, 'favorite'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        book_id: id,
        visited_id: customer_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  #検索メソッド、タイトルと内容をあいまい検索する
  def self.search(keyword)
    Book.where(['title LIKE ? OR caption LIKE ?', "%#{keyword}%", "%#{keyword}%"])
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    # Destroy
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    # Create
    new_tags.each do |new|
      newtag = Tag.find_or_create_by(name: new)
      self.tags << newtag
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@customers=Customer.all
		# 会員情報を全てインスタンスに挿入
	end

	def show
		@customer=Customer.find(params[:id])
	end

	def edit
		@customer=Customer.find(params[:id])
	end

	def update
		@customer=Customer.find(params[:id])
		if @customer.update(customer_params)
		   redirect_to admins_customer_path(@customer.id)
		else
      		render "edit"
    	end
	end

	private
	def customer_params
		params.require(:customer).permit(:name,:introduction,:image_id,:back_image_id,:is_member,:email)
	end
end

app/controllers/customers/book_tags_controller.rb
class Customers::BookTagsController < ApplicationController

end

app/controllers/customers/books_controller.rb
class Customers::BooksController < ApplicationController
	before_action :authenticate_customer!, only: [:new,:create, :edit, :update, :destroy]
  before_action :correct_customer, only: [:edit, :update, :destroy]

	def new
    @person = Person.find(params[:person_id])
		@book = Book.new
      respond_to do |format|
        format.html
        format.json
      end
	end

	def index
    if params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      books = @tag.books.order(created_at: :desc)
    else
      books = Book.all.order(created_at: :desc)
    end
    @tag_lists = Tag.all
    @books = Kaminari.paginate_array(books).page(params[:page]).per(10)
	end

  def search
    @tag_lists = Tag.all
    @books = Book.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

	def create
		person = Person.find(params[:person_id])
    	@book = Book.new(book_params)
    	@book[:person_id] = person.id
    	@book[:customer_id] = current_customer.id
      tag_list = params[:book][:name].split(nil)
    	if @book.save
         @book.save_tag(tag_list)
         flash[:notice] = "新しく本を登録しました！"
    	   redirect_to person_path(person.id)
    	else
    		render "new"
    	end
  end

  def edit
    @book = Book.find(params[:id])
    @person = Person.find(@book.person_id)
    @tag_list = @book.tags.pluck(:name).join(" ")
  end

  def update
    @book = Book.find(params[:id])
    @book[:customer_id] = current_customer.id
    tag_list = params[:book][:name].split(nil)
      if @book.update(book_params)
       @book.save_tag(tag_list)
         redirect_to person_path(params[:person_id])
      else
           render "edit"
      end
  end

	def destroy
     @book = Book.find(params[:id])
     @book.destroy
     if params[:customer_id].present?
      @customer = Customer.find(params[:customer_id])
      redirect_to @customer
      return
     else
      redirect_to person_path(params[:person_id])
      return
     end
	end

private
	def book_params
    	params.require(:book).permit(:title,:caption,:image_url,:person_id,:customer_id,:grade,:scribble)
  	end
  def correct_customer
   @book = current_customer.books.find_by(id: params[:id])
    unless @book
      redirect_to home_path
    end
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/creations_controller.rb
class Customers::CreationsController < ApplicationController
	before_action :authenticate_customer!
	before_action :correct_customer, only: [:edit, :update, :destroy]

	def new
		@creation = Creation.new
		@person = Person.find(params[:person_id])
	end

	def index
		@creation = Creation.all
	end

	def create
		person = Person.find(params[:person_id])
		@creation = Creation.new(creation_params)
		@creation[:person_id] = person.id
		@creation[:customer_id] = current_customer.id
		if @creation.save
			flash[:notice] = "作品が登録されました"
			redirect_to person_path(person.id)
		else
    	   render :new
    	end
	end

	def edit
		@creation = Creation.find(params[:id])
		@person = Person.find(@creation.person_id)
	end

	def update
		@creation = Creation.find(params[:id])
		@creation[:customer_id] = current_customer.id
		if  @creation.update(creation_params)
			flash[:notice] = "作品情報が更新されました"
			redirect_to person_path(params[:person_id])
		else
    	  render "edit"
    	end
	end

	def destroy
		person = Person.find(params[:person_id])
		@creation = Creation.find(params[:id])
  		@creation.destroy
  			redirect_to person_path(person.id)

    end
private

  def creation_params
	params.require(:creation).permit(:customer_id, :person_id, :image, :cartoon, :caption)
  end
   def correct_customer
   @creation = current_customer.creations.find_by(id: params[:id])
    unless @creation
      redirect_to home_path
    end
end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
	before_action :authenticate_customer!, except: [:show]
	before_action :correct_customer, only: [:edit, :update, :destroy]

	def show
		@people =Person.all
		@customer = Customer.find(params[:id])
		@books = @customer.books
		@favorites = Favorite.where(customer_id: @customer.id)
		@like_books = Book.find(@favorites.pluck(:book_id))
		@portraits = @customer.portraits

	end

	def edit
		@customer = current_customer
	end

	def update
	 	@customer = current_customer
      if  @customer.update(customer_params)
     	  redirect_to customer_path(@customer.id)
      else
    	render "edit"
      end
	end

	def destroy
		@customer = Customer.find(params[:id])
		@customer.destroy
		redirect_to home_path
	end

	def destruction
	end
private
	def customer_params
    	params.require(:customer).permit(:name,:introduction,:image,:back_image,:is_member,:email)
  	end

  	def correct_customer
     customer = Customer.find(params[:id])
     if current_customer != customer
      redirect_to customer_path(current_customer)
     end
    end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
	def create
		    book = Book.find(params[:book_id])
            favorite = current_customer.favorites.new(book_id: book.id)
    		favorite.save
            book.create_notification_by(current_customer)
            redirect_to person_path(params[:person_id])
	end


	def destroy
			book = Book.find(params[:book_id])
    		favorite = current_customer.favorites.find_by(book_id: book.id)
    		favorite.destroy
    		redirect_to person_path(params[:person_id])
    end

private
    def favorite_params
        params.require(:favorite).permit(:person_id,:customer_id)
    end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

	def top
		@people = Person.all.order(created_at: :desc).page(params[:page]).per(6)
		@portraits = Portrait.all
		@advertisements = Person.all.select do |person|
			person.portraits.empty?
		end
		@book = Book.all
		@unregistereds = Person.all.select do |person|
			person.books.empty?
		end
	end

	def about
	end

	def how_to_use
	end

	def privacy
	end

end

app/controllers/customers/notifications_controller.rb
class Customers::NotificationsController < ApplicationController
	def index
		#current_customerの投稿に紐づいた通知一覧
		@notifications = current_customer.passive_notifications
		#@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    	@notifications.where(checked: false).each do |notification|
      		notification.update_attributes(checked: true)
    	end
  	end

  	def destroy
      #通知を全削除
        @notifications = current_customer.passive_notifications.destroy_all
        redirect_to notifications_path
    end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/people_controller.rb
class Customers::PeopleController < ApplicationController
	before_action :authenticate_customer!, except: [:show, :index]
	def new
	  @person = Person.new
	end

	def index
		@people = Person.order(:name_kana)
	end

	def search
		@people = Person.search(params[:keyword]).order(:name_kana)
		@keyword = params[:keyword]
		render "index"
	end

	def show
		@person = Person.find(params[:id])
		@beginners = @person.books.where(grade: 'beginner').page(params[:page]).per(5)
		@professionals = @person.books.where(grade: 'professional').page(params[:page]).per(5)
		@creations = @person.creations.page(params[:page]).per(10)
		@portrait =Portrait.new
	end

	def create
    	@person = Person.new(person_params)
    	if	@person.save
    		flash[:notice] = "新しく偉人を登録しました！"
    		redirect_to person_path(@person.id)
    	else
    		render action: :new
		end
	end

	def edit
		@person = Person.find(params[:id])
	end

	def update
		@person = Person.find(params[:id])
    	if @person.update(person_params)
    	   redirect_to person_path(@person.id)
    	else
      	   render "edit"
    	end
	end

private
	def person_params
		params.require(:person).permit(:name,:name_kana,:alias,:country,:introduction,:birth,:death,:person_image_id,:customer_id)
	 end
end

app/controllers/customers/portraits_controller.rb
class Customers::PortraitsController < ApplicationController
	before_action :authenticate_customer!

	def index
		@portraits = Portrait.all
		@person = Person.new
	end
	def create
		@person = Person.find(params[:person_id])
		@portrait =Portrait.new(portrait_params)
		@portrait[:person_id] = @person.id
		@portrait[:customer_id] = current_customer.id
	  if @portrait.save
	     flash[:notice] = "肖像画が登録されました."
	     redirect_to person_path(@person.id)
	  else
	     redirect_to person_path(@person.id)
	  end
	end

	def destroy
		portrait = Portrait.find(params[:id])
  		portrait.destroy
  			redirect_to customer_path(current_customer.id)

	end

private
	def portrait_params
	  params.require(:portrait).permit(:customer_id, :person_id, :image)
 	end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/tags_controller.rb
class Customers::TagsController < ApplicationController

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/customers/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="youtube-container ">
        <% iframe = content_tag(
          :iframe,
          '',
          width: 660,
          height: 450,
          src: "https://youtu.be/-5CBBoPqbA4?start=29",
          frameborder: 0,
          allowfullscreen: true
        ) %>
        <%= content_tag(:div, iframe, class: 'youtube-container') %>
      </div>
      <p class="information-search">資料情報検索<span class="postscript"> (ISBNかCNII論文IDがお分かりでない方は、お手数ですが史料登録フォームの項目を直接入力ください)</span></p>
    </div>
    <div class="col-lg-6"><section class="search-box">
      <div class="result">
        <strong class="ISBN_search" id="title-search">本検索（ISBN使用）</strong>
 　　　　<div class = "panel-title">
          <div class="ISBN_input">ISBN13：<input id="isbn" type="text" name="isbn" value="" autofocus>
            <button id="getBookInfo" class="btn btn-default">書籍情報取得</button>
 　　      </div>
 　　      <div class="book__topic"><p id="thumbnail"></p></div>
          <div class="book__topic">書籍名：<span id="title"></span></div>
          <div class="book__topic">出版社：<span id="publisher"></span></div>
          <div class="book__topic">巻：<span id="publisher"></span></div>
          <div class="book__topic">シリーズ：<span id="series"></span></div>
          <div class="book__topic">著者：<span id="author"></span></div>
          <div class="book__topic">出版日：<span id="author"></span></div>
          <div class="book__topic">サムネイルURI：<span id="cover"></span></div>
          <div class="book__topic">詳細：<span id="description"></span>
          </div>
        </div>
      </div><section class="search-box">
    </div>
    <div class="col-lg-6"><section class="search-box">
      <div class="essay_result">
        <strong class="NAID_search" id="essay_title-search">論文情報検索（NAID使用）</strong>
        <div class = "panel-title">
          <div class="NAID_input">CNII論文ID(NAID)：<input id="naid" type="text" name="naid" value="" autofocus>
            <button id="getEssayInfo" class="btn btn-default">論文情報取得</button>
          </div>
          <div class="book__topic">論文タイトル：<span id="essay_title"></span></div>
          <div class="book__topic">出版社名：<span id="essay_publisher"></span></div>
          <div class="book__topic">刊行物名：<span id="essay_publicationName"></span></div>
          <div class="book__topic">巻：<span id="essay_volume"></span></div>
          <div class="book__topic">号：<span id="essay_number"></span></div>
          <div class="book__topic">著者名：<span id="essay_creator"></span></div>
          <div class="book__topic">出版日：<span id="essay_pubdate"></span></div>
          <div class="book__topic">抄録：<span id="essay_description"></span>
          </div>
          <div class="book__topic"> 外部リンクに関する記述：<span id="essay_link"></span>
          </div>
        </div>
      </div><section class="search-box">
    </div>
    <div class="col-lg-12">
    <h4><mark>史料情報編集</mark></h4>
      <%= form_with(model: @book , url: person_book_path, local: true) do |f| %>
        <%# エラーメッセージ　%>
        <%= render 'layouts/error_messages', model: f.object %>
        <%# ここまでエラ-メッセージ　%>
        <p class ="book-form-title">■タイトル、著者名、出版社<span class="mandatory">必須</span></p>
        　<span class="form-a"><%= f.text_area :title ,id: "book-name" ,size:"100" %></span>
        <p class ="book-form-title">■感想<span class="mandatory">必須</span></p>
        　<span class="form-a"><%= f.text_area :caption ,size:"100" %></span>
        <div class="grade_radio_button">
        　<p class ="book-form-title">■本の種類<span class="mandatory">必須</span></p>
          <label><%= f.radio_button :grade, 'beginner' %> 初心者向け</label>
          <label><%= f.radio_button :grade, 'professional' %> その他（中級者以上向け）</label>
        </div>
        <p class ="book-form-title">■感想絵</p>
          <%= f.attachment_field :scribble %>
        <p class ="book-form-title">■タグ<span class ="form-title">(半角スペースを入力することで複数のタグを付けることができます)
        </span></p>
        <p>例：聖徳太子 与謝野晶子 ルター</p>
          <div class="book-tags-field">
            <%= f.text_field :name, value: @tag_list, size:"100" %>
          </div>
        <%# 非表示用サムネイルURL%>
        <span class="form-a" ><%= f.text_area :image_url ,disaled: "true", id: "image_url" ,style: "visibility: hidden", hide_label:"true" %></span><br>
          <%= f.submit "編集内容を保存する"%>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 style="padding-top: 20px;"><mark>タグ絞り込み検索</strong></mark>
       <%= link_to "リセット", books_path,class: "btn btn-sm "%>
      </h4>
      <li class="search_friend_by_categorize">
        <% @tag_lists.each do |list| %>
          <%= link_to list.name, books_path(tag_id: list.id), class: 'tag_list' %>
        <% end %>
      </li>
      <P class="book_name_search"><strong>ワード検索</strong><span class="attention">（本のタイトル、感想文からヒットするものを検索します)</span></p>
      <%= form_with url: books_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "ワード検索" %>
      <% end %>
      <h4><mark> 本一覧 </mark></h4>
      <table class="table-responsive">
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= attachment_image_tag book, :scribble, :fill, 125, 125, fallback: "/images/no_image.jpg" %>
              <div><strong>投稿者 <%= link_to book.customer.name, customer_path(book.customer.id) %></strong></div>
            </td>
            <td>
              <div>
                <strong><%= book.title%></strong><br>
                <%= book.caption %>
              <%# ここからいいねボタン%>
              <% if current_customer != nil && book.person_id != nil%>
                <% if book.favorited_by?(current_customer) %>
                  <%= link_to dislike_path(person_id: book.person_id, book_id: book.id), method: :delete, class: "float-left dislike" do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"> <%= book.favorites.count %> いいね</i>
                  <% end %>
                <% else %>
                  <%= link_to like_path(person_id: book.person_id, book_id: book.id), method: :post, class: "float-left like" do %>
                    <i class="fa fa-heart-o"> <%= book.favorites.count %> いいね</i>
                  <% end %>
                <% end %>
              <% end %>
              </div>
              <p class="tag_list_box">
              <% book.tags.each do |tag| %>
                <% if book.person_id != nil%>
                  <%=link_to "#{tag.name}", person_path(book.person.id), class: 'smaller tag_list' %>
                <% end %>
              <% end %>
              </p>
            <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/customers/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="youtube-container ">
        <% iframe = content_tag(
          :iframe,
          '',
          width: 660,
          height: 450,
          src: "https://youtu.be/-5CBBoPqbA4?start=29",
          frameborder: 0,
          allowfullscreen: true
        ) %>
        <%= content_tag(:div, iframe, class: 'youtube-container') %>
      </div>
      <p class="information-search">資料情報検索<span class="postscript"> (ISBNかCNII論文IDがお分かりでない方は、お手数ですが史料登録フォームの項目を直接入力ください)</span></p>
    </div>
    <div class="col-lg-6"><section class="search-box">
      <div class="result">
        <strong class="ISBN_search" id="title-search">本検索（ISBN使用）</strong>
        <div class = "panel-title">
          <div class="ISBN_input">ISBN13：<input id="isbn" type="text" name="isbn" value="" autofocus>
            <button id="getBookInfo" class="btn btn-default">書籍情報取得</button></div>
 　　      <div class="book__topic"><p id="thumbnail"></p></div>
          <div class="book__topic">書籍名：<span id="title"></span></div>
          <div class="book__topic">出版社：<span id="publisher"></span></div>
          <div class="book__topic">巻：<span id="publisher"></span></div>
          <div class="book__topic">シリーズ：<span id="series"></span></div>
          <div class="book__topic">著者：<span id="author"></span></div>
          <div class="book__topic">出版日：<span id="author"></span></div>
          <div class="book__topic">サムネイルURI：<span id="cover"></span></div>
          <div class="book__topic last">詳細：<span id="description"></span></div>
        </div>
      </div></section>
    </div>
    <div class="col-lg-6"><section class="search-box">
      <div class="essay_result">
        <strong class="NAID_search" id="essay_title-search">論文情報検索（NAID使用）</strong>
        <div class = "panel-title">
          <div class="NAID_input">CNII論文ID(NAID)：<input id="naid" type="text" name="naid" value="" autofocus>
            <button id="getEssayInfo" class="btn btn-default">論文情報取得</button>
          </div>
          <div class="book__topic">論文タイトル：<span id="essay_title"></span></div>
          <div class="book__topic">出版社名：<span id="essay_publisher"></span></div>
          <div class="book__topic">刊行物名：<span id="essay_publicationName"></span></div>
          <div class="book__topic">巻：<span id="essay_volume"></span></div>
          <div class="book__topic">号：<span id="essay_number"></span></div>
          <div class="book__topic">著者名：<span id="essay_creator"></span></div>
          <div class="book__topic">出版日：<span id="essay_pubdate"></span></div>
          <div class="book__topic">抄録：<span id="essay_description"></span></div>
          <div class="book__topic"> 外部リンクに関する記述：<span id="essay_link"></span></div>
        </div>
      </div>
    </div></section>
    <div class="col-lg-12">
    <h4><mark><strong>新規史料登録</strong></mark></h4>

    <div class="result-image">

      <%= form_with(model: @book ,id:"form-result", url: person_books_path, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <p class ="book-form-title">■タイトル、著者名、出版社<span class="mandatory">必須</span></p>
          <span class="form-a"><%= f.text_field :title ,id: "book-name" ,size:"100"%></span>
        <p class ="book-form-title">■感想<span class="mandatory">必須</span></p>
          <span class="form-a"><%= f.text_area :caption ,id: "caption" ,size:"100"%>
          </span><br>
        <div class="grade_radio_button">
          <p class ="book-form-title">■本の種類<span class="mandatory">必須</span></p>
          <label>
            <%= f.radio_button :grade, 'beginner' %> 初心者向け</label>
          <label>
            <%= f.radio_button :grade, 'professional' %> その他（中級者以上向け）</label>
        </div>
        <p class ="book-form-title">■感想絵</p>
          <%= f.attachment_field :scribble %>
        <%# 非表示用サムネイルURL%>
        <span class="form-a" ><%= f.text_area :image_url ,disaled: "true", id: "image_url" ,style: "visibility: hidden", hide_label:"true" %>
        </span><br>
        <p class ="book-form-title">■タグ</p>
        <p class ="form-title">半角スペースを入力することで複数のタグを付けることができます。<br>
           例：聖徳太子 与謝野晶子 ルター</p>
        <%= f.text_field :name, size:"100"%>
        <%= f.submit '投稿' %>
      <% end %>
    </div>
    </div>

  </div>
</div>