config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
  	sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }
 #上はデバイスのコントローラのカスタマイズ

  get '/' => "customers/homes#top", as: 'home'
  get 'homes/about' => "customers/homes#about",as: 'about'
  get 'homes/how_to_use' => "customers/homes#how_to_use",as: 'how_to_use'
  get 'homes/privacy' => "customers/homes#privacy",as: 'privacy'
  get '/people/search' => 'customers/people#search'
  get '/books/search' => 'customers/books#search'
  post '/people/:person_id/books/:book_id/favorites' => "customers/favorites#create", as: "like"
  delete '/people/:person_id/books/:book_id/favorites' => "customers/favorites#destroy", as: "dislike"

  scope module: 'customers' do
    resources :customers, only:[:edit, :update, :destroy, :show]
    get 'customer/destruction'=> "customers#destruction"
    resources :notifications, only: [:index, :destroy]
    resources :books, only: [:index,:destroy]
    resources :people, only:[:index, :create, :show, :edit, :update, :new] do
      resources :portraits, only:[:index, :create, :destroy]
      resources :creations, only:[:new,:index, :create, :edit, :update, :destroy]
      resources :books, only:[:new,  :create, :edit, :update, :destroy]
    end
  end
    devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :people, only: [:index, :destroy]
    resources :tags, only: [:index, :destroy, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :customer
	belongs_to :person, optional: true
	has_many :favorites, dependent: :destroy
	has_many :notifications, dependent: :destroy
  has_many :book_tags, dependent: :destroy, foreign_key: 'book_id'
  has_many :tags, through: :book_tags
  attachment :scribble
	validates :title, presence:true
	validates :caption, presence:true
  validates :grade, presence:true

	def favorited_by?(customer)
		favorites.where(customer_id: customer.id).exists?
	end

  def create_notification_by(current_customer)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and book_id = ? and action = ? ",
                                  current_customer.id, customer_id, id, 'favorite'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        book_id: id,
        visited_id: customer_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  #検索メソッド、タイトルと内容をあいまい検索する
  def self.search(keyword)
    Book.where(['title LIKE ? OR caption LIKE ?', "%#{keyword}%", "%#{keyword}%"])
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    # Destroy
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end
    # Create
    new_tags.each do |new|
      newtag = Tag.find_or_create_by(name: new)
      self.tags << newtag
    end
  end
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag

  validates :book_id, presence:true
  validates :tag_id, presence:true
end

app/models/creation.rb
class Creation < ApplicationRecord
	belongs_to :customer
	belongs_to :person
	attachment :image
	attachment :cartoon

	validates :image, presence:true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :people
  has_many :books, dependent: :destroy
  has_many :portraits, dependent: :destroy
  has_many :creations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attachment :image

  enum is_member: {Available: true, Invalid: false}
  validates :is_member, inclusion: { in: ["Available", "Invalid"] }
  #有効会員はtrue、退会済み会員はfalse
   def active_for_authentication?
        super && (self.is_member === "Available")
   end
  #is_memberが有効の場合は有効会員(ログイン可能)

  validates :name,
	presence: true

  after_create :send_welcome_mail
  def send_welcome_mail
    CustomerMailer.customer_welcome_mail(self).deliver
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :customer
	belongs_to :book

end

app/models/notification.rb
class Notification < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
	belongs_to :book, optional: true

	belongs_to :visitor, class_name: 'Customer', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'Customer', foreign_key: 'visited_id', optional: true
end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :customer, optional: true
	has_many :books, :dependent => :nullify
  has_many :portraits
  has_many :creations
  has_one :tag, :dependent => :nullify
  	validates :name, presence:true
  	validates :name_kana,format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }
    validates :birth, numericality: { only_integer: true }, allow_blank: true
    validates :death, numericality: { only_integer: true }, allow_blank: true
  def self.search(keyword)
      where(["name like? OR alias like? OR name_kana like?","%#{keyword}%","%#{keyword}%","%#{keyword}%"])
  end
end

app/models/portrait.rb
class Portrait < ApplicationRecord
	belongs_to :customer
	belongs_to :person
	attachment :image

  	validates :image, presence:true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :book_tags, dependent: :destroy, foreign_key: 'tag_id'
	has_many :books, through: :book_tags
	belongs_to :person, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :set_host
  def set_host
    Rails.application.routes.default_url_options[:host] = request.host_with_port
  end
	protected
	#サインイン後の遷移先指定
	def after_sign_in_path_for(resource)
		home_path
	end
    #サインアップ後の遷移先指定
    def after_sign_up_path_for(resource)
    　home_path
    end
    #ログアウト後の遷移先指定
    def after_sign_out_path_for(resource)
      home_path
    end

	def configure_permitted_parameters
       	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 	end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/people_helper.rb
module Admins::PeopleHelper
end

app/helpers/admins/tags_helper.rb
module Admins::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/books_helper.rb
module Customers::BooksHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/people_helper.rb
module Customers::PeopleHelper
end

app/helpers/customers/tags_helper.rb
module Customers::TagsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Numare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/fe584cea55.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="toggler__txt">メニュー</span>
      <% if customer_signed_in? %>
        <span class="マイページ"></span>
        <span class="通知"></span>
        <span class="使い方"></span>
        <span class="偉人一覧"></span>
        <span class="本検索"></span>
        <span class="ログアウト"></span>
        <span class="偉人登録"></span>
      <% elsif  admin_signed_in? %>
        <span class="登録者一覧"></span>
        <span class="偉人一覧"></span>
        <span class="タグ一覧"></span>
        <span class="ログアウト"></span>
      <% else %>
        <span class="使い方"></span>
        <span class="人物一覧"></span>
        <span class="本一覧"></span>
        <span class="新規登録"></span>
        <span class="ログイン"></span>
        <span class="テスト会員ログイン情報"></span>
        <span class="偉人登録"></span>
      <% end %>
      </button>
      <%= link_to image_tag("/images/logo.png", class: "logo" ,size: '95x95'), home_path %>
      <%#<strong><%= link_to "偉人登録", new_person_path, class:"btn-push" %>
      </strong>
    </div>
    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-left navbar-collapse collapse">
        <% if customer_signed_in? %>
          <li class='navbox'>
           <%= link_to 'マイページ', customer_path(current_customer.id), class:"" %></li>
          <li class='navbox'>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle"></i>
            <% end %>
            <%= link_to "通知", notifications_path , class:"for_up" %>
          </li>
           <li class='navbox'>
            <%= link_to "使い方", how_to_use_path, class:"" %></li>
          <li class='navbox'>
            <%= link_to "偉人一覧", people_path, class:"" %></li>
          <li class='navbox'>
            <%= link_to "本検索", books_path, class:"" %></li>
          <li class='navbox'>
            <%= link_to "ログアウト", destroy_customer_session_path, class:"", method: :delete %></li>
          <li class='navbox_people'>
            <strong><%= link_to "偉人登録", new_person_path, class:"btn-circle-border-double" %>
           </strong>
          </li>
        <% elsif  admin_signed_in? %>
          <li class='navbox'>
            <%= link_to '登録者一覧', admins_customers_path, class:"" %></span></li>
          <li class='navbox'>
            <%= link_to '偉人一覧', admins_people_path, class:"" %></span></li>
          <li class='navbox'>
            <%= link_to 'タグ一覧', admins_tags_path, class:"" %></span></li>
          <li class='navbox'>
            <%= link_to "ログアウト", destroy_admin_session_path, class:"", method: :delete %></li>
        <% else %>
          <li class='navbox'>
            <%= link_to "使い方", how_to_use_path, class:"" %></li>
          <li class='navbox'>
            <%= link_to '人物一覧', people_path , class:"" %></li>
          <li class='navbox'>
            <%= link_to "本一覧", books_path, class:"" %></li>
          <li class='navbox new_button' >
            <span><%= link_to "新規登録", new_customer_registration_path, class:"s-button" %>
            </span>
          </li>
          <li class='navbox login_button' >
            <span><%= link_to "ログイン", new_customer_session_path, class:"l-button"%>
            </span>
          </li>
          <li class='navbox_people'>
            <strong><%= link_to "偉人登録", new_person_path, class:"btn-circle-border-double"%>
            </strong>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
  </header>
  <div class="wrapper">
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="container text-center">
      <p>使用API： openBD  |  CiNii Web API <br>
        利用規約  ｜ <%= link_to "プライバシーポリシー", privacy_path %><br>
        ©︎ 2020 Numare</p>
    </div>
  </footer>
  </body>
</html>